### PR TITLE
:steamhappy: 2

### PR DESCRIPTION
**Pull request by slonkazoid**
### slonkazoid

- [x] backend cleanup
- [x] frontend cleanup
- [x] server max file and file count -> js

### pandarose_

- [ ] fix files.colon3.lol ui

### chxry

- [x] "clean anything that looks like a mess"
- [x] make uploaded files list look a bit cooler 
- [x] quick response codes

### CODE REVIEW

**Comment by callmewoem** [comment]
what are you cooking, i want to cook aswell

**Comment by callmewoem** [comment]
fixed conflict in readme.md

**Comment by slonkazoid** [comment]
what is "cache"

**Comment by slonkazoid** [comment]
todo: qr

**Comment by slonkazoid** [comment]
looks gay to me :rocket: :star: :star2:

**Comment by chxry** [comment]
fr 🏳️‍🌈✨

**Review by callmewoem — APPROVED** [review]
yeah

**Pull request merged**
